title: Kot Karoche
description: "Стиль жизни, DIY и уютные лайфхаки от кота 🐱"

# подключаем remote-тему Architect
remote_theme: pages-themes/architect@v3

# отключаем стандартную тему, чтобы не конфликтовала
theme: null

# плагин для загрузки remote_theme
plugins:
  - jekyll-remote-theme

# (опционально) доп. кастомизация Architect
architect:
  header:
    background: light
  footer:
    info: "© 2025 Mahvash"
