title: Kot Karoche
description: "Стиль жизни, DIY и уютные лайфхаки от кота 🐱"
url: "https://kotkaroche.github.io/Mahvash"
author: "Mahvash"
lang: "ru"

# подключаем remote-тему Architect
remote_theme: pages-themes/architect@v0.2.0

# отключаем стандартную тему, чтобы не конфликтовала
theme: null

# плагин для загрузки remote_theme
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# (опционально) доп. кастомизация Architect
architect:
  header:
    background: light
  footer:
    info: "© 2025 Mahvash"
